sudo: required
services:
  - docker

before_install:
  - docker build -t andrademarco/simple-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andrademarco/simple-docker-react npm run test
