version: '3'
services:
  simple-react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: # mapping
      - /app/node_modules # do not map node_modules
      - .:/app # map /app to current working directory
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]